#
# Module manifest for module 'Get-DiskUsage'
#
# Generated by: Darrick Ross
# Generated on: 2025-10-18
#

@{
    RootModule           = 'Get-DiskUsage.psm1'
    ModuleVersion        = '1.0.0'
    GUID                 = '4eea5430-4d8c-4dbd-92d6-23d0a72745e2'

    Author               = 'Darrick Ross'
    CompanyName          = 'Unknown'
    Copyright            = '(c) Darrick Ross. All rights reserved.'
    Description          = 'du-like disk usage command with exclude patterns, depth limiting, and human-readable sizes.'

    # Compatibility
    PowerShellVersion    = '5.1'
    CompatiblePSEditions = @('Desktop', 'Core')

    # Dependencies
    RequiredModules      = @()
    RequiredAssemblies   = @()

    # Pipeline setup
    ScriptsToProcess     = @()
    TypesToProcess       = @()
    FormatsToProcess     = @()
    NestedModules        = @()

    # Exports
    FunctionsToExport    = @('Get-DiskUsage')
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @('du')

    # Packaging
    ModuleList           = @()
    FileList             = @('Get-DiskUsage.psm1')

    PrivateData          = @{
        PSData = @{
            Tags = @('du', 'disk', 'usage', 'filesystem', 'powershell')
            # LicenseUri               = ''
            # ProjectUri               = ''
            # IconUri                  = ''
            # ReleaseNotes             = 'Initial public release.'
            # Prerelease               = ''
            # RequireLicenseAcceptance = $false
            # ExternalModuleDependencies = @()
        }
    }

    # HelpInfoURI           = ''
    # DefaultCommandPrefix  = ''
}
